image: "rust:slim"

stages:
  - check
  - build
  - test
  - release

# Variable defaults
variables:
  RUST_VERSION: stable
  RUST_TARGET: x86_64-unknown-linux-gnu

# Cache rust/cargo/build artifacts
cache:
  key: "$CI_PIPELINE_ID-$RUST_VERSION"
  paths:
    - /usr/local/cargo/registry/
    - /usr/local/rustup/toolchains/
    - /usr/local/rustup/update-hashes/
    - target/

# Install compiler
before_script:
  - |
    rustup install $RUST_VERSION
    rustup default $RUST_VERSION
  - |
    rustc --version
    cargo --version

# Check on stable, beta and nightly 
.check-base: &check-base
  stage: check
  script:
    - cargo check --verbose
check-stable:
  <<: *check-base
check-beta:
  <<: *check-base
  variables:
    RUST_VERSION: beta
check-nightly:
  <<: *check-base
  variables:
    RUST_VERSION: nightly
check-old:
  <<: *check-base
  variables:
    RUST_VERSION: "1.40.0"

# Build using Rust stable
build-x86_64-linux-gnu:
  stage: build
  needs:
    - check-stable
  script:
    - cargo build --target=$RUST_TARGET --release --verbose
    - mv target/$RUST_TARGET/release/rp2g ./rp2g-$RUST_TARGET
    - strip -g ./rp2g-$RUST_TARGET
  artifacts:
    name: rp2g-x86_64-linux-gnu
    paths:
      - rp2g-$RUST_TARGET
    expire_in: 1 month

# Build a static version
build-x86_64-linux-musl:
  stage: build
  needs:
    - check-stable
  variables:
    RUST_TARGET: x86_64-unknown-linux-musl
  script:
    - rustup target add $RUST_TARGET
    - cargo build --target=$RUST_TARGET --release --verbose

    # Prepare the release artifact, strip it
    - find . -name rp2g -exec ls -lah {} \;
    - mv target/$RUST_TARGET/release/rp2g ./rp2g-$RUST_TARGET
    - strip -g ./rp2g-$RUST_TARGET
  artifacts:
    name: rp2g-x86_64-linux-musl
    paths:
      - rp2g-$RUST_TARGET
    expire_in: 1 month

# Run the unit tests through Cargo
test-cargo:
  stage: test
  needs:
    - check-stable
  dependencies: []
  script:
    - cargo test --verbose

# # Cargo crate release
# release-crate:
#   stage: release
#   dependencies: []
#   only:
#     - /^v(\d+\.)*\d+$/
#   script:
#     - echo "Creating release crate to publish on crates.io..."
#     - echo $CARGO_TOKEN | cargo login
#     - echo "Publishing crate to crates.io..."
#     - cargo publish --verbose --allow-dirty
